### PR TITLE
Collector faban

### PR DESCRIPTION
**Pull request by Cerfoglg**
Added faban collector
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/benchflow/collectors/pull/62%23issuecomment-220773537%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/62%23issuecomment-220827663%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/62%23issuecomment-220827667%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/62%23issuecomment-220827673%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benchflow/collectors/pull/62%23issuecomment-220773537%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Ignore%20this%20one%22%2C%20%22created_at%22%3A%20%222016-05-21T11%3A49%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-05-22T11%3A34%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22Closed%20in%20favour%20of%20https%3A//github.com/benchflow/collectors/pull/63%22%2C%20%22created_at%22%3A%20%222016-05-22T11%3A34%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-05-22T11%3A34%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/benchflow/collectors/pull/62#issuecomment-220773537'>General Comment</a></b>
- <a href='https://github.com/Cerfoglg'></a> Ignore this one
- <a href='https://github.com/VincenzoFerme'></a> :+1:
- <a href='https://github.com/VincenzoFerme'></a> Closed in favour of https://github.com/benchflow/collectors/pull/63

<a href='https://www.codereviewhub.com/benchflow/collectors/pull/62?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benchflow/collectors/pull/62?approve=1'></a>&nbsp;<a href='https://github.com/benchflow/collectors/pull/62'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by VincenzoFerme** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/benchflow/collectors/pull/62'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Cerfoglg** [comment]
Ignore this one

**Comment by VincenzoFerme** [comment]
:+1:

**Comment by VincenzoFerme** [comment]
Closed in favour of https://github.com/benchflow/collectors/pull/63

**Comment by VincenzoFerme** [comment]
:+1:

**Pull request closed without merging**
