### PR TITLE
Faban collector

### LINKED ISSUE #36: Implement a Collector that Collects Faban data
We have to implement a collector, or use the [zip](https://github.com/benchflow/collectors/tree/dev/files/zip) if feasible, that collect faban data from the following folder inside the [`faban-harness`](https://github.com/benchflow/docker-images/tree/dev/faban/harness) container:
- ${FABAN_HOME}/output/${FABAN_RUN_ID}

### PR DESCRIPTION
**Pull request by Cerfoglg**
Added collector for faban data

fixes #36
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/benchflow/collectors/pull/61%23issuecomment-220772281%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/61%23issuecomment-220773584%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/61%23issuecomment-220774355%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/61%23issuecomment-220775298%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/61%23issuecomment-220803160%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/61%23issuecomment-220826814%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/61%23issuecomment-220827714%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/61%23issuecomment-220827726%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benchflow/collectors/pull/61%23issuecomment-220772281%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Cerfoglg%20there%20is%20something%20wrong%20in%20this%20pull%20request.%20The%20changes%20to%20the%20%60stats%60%20collectors%20are%20committed%20again.%20Ping%20me%20when%20solved%2C%20please.%22%2C%20%22created_at%22%3A%20%222016-05-21T11%3A16%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40VincenzoFerme%20It%20doesn%27t%20work%2C%20it%20just%20keeps%20all%20the%20commits%20for%20no%20reason.%22%2C%20%22created_at%22%3A%20%222016-05-21T11%3A50%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20seems%20it%20is%20because%20you%20actually%20have%20those%20commits%20in%20the%20branch%20from%20where%20you%20are%20performing%20the%20pull%20request%3A%20https%3A//github.com/Cerfoglg/collectors/commits/faban-collector%5Cr%5Cn%5Cr%5CnIt%20seems%20that%20one%20solution%20would%20be%20to%20have%20a%20new%20branch%20and%20%60cherry-pick%60%20only%20the%20commits%20that%20actually%20add%20something%20new%3A%20http%3A//mispdev.blogspot.it/2013/02/github-cherry-picking-commits-from-pull.html.%20Then%20commit%20that%20branch.%22%2C%20%22created_at%22%3A%20%222016-05-21T12%3A10%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40VincenzoFerme%20It%20won%27t%20let%20me%2C%20it%20still%20shows%20all%20the%20commits.%20Creating%20new%20branches%20just%20bring%20in%20all%20the%20commits%20for%20the%20properties%20and%20stats%20as%20well%22%2C%20%22created_at%22%3A%20%222016-05-21T12%3A30%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40Cerfoglg%20are%20you%20creating%20a%20new%20branch%20from%20your%20%60dev%60%20branch%20after%20you%20synch%20your%20%60dev%60%20branch%20with%20the%20%60dev%60%20branch%20of%20the%20benchflow%20repository%3F%22%2C%20%22created_at%22%3A%20%222016-05-21T22%3A14%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40VincenzoFerme%20Found%20a%20workaround%2C%20see%20%2363%22%2C%20%22created_at%22%3A%20%222016-05-22T11%3A13%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%2C%20%7B%22body%22%3A%20%22Closed%20in%20favour%20of%20https%3A//github.com/benchflow/collectors/pull/63%22%2C%20%22created_at%22%3A%20%222016-05-22T11%3A35%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-05-22T11%3A36%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/benchflow/collectors/pull/61#issuecomment-220772281'>General Comment</a></b>
- <a href='https://github.com/VincenzoFerme'></a> @Cerfoglg there is something wrong in this pull request. The changes to the `stats` collectors are committed again. Ping me when solved, please.
- <a href='https://github.com/Cerfoglg'></a> @VincenzoFerme It doesn't work, it just keeps all the commits for no reason.
- <a href='https://github.com/VincenzoFerme'></a> It seems it is because you actually have those commits in the branch from where you are performing the pull request: https://github.com/Cerfoglg/collectors/commits/faban-collector
  It seems that one solution would be to have a new branch and `cherry-pick` only the commits that actually add something new: http://mispdev.blogspot.it/2013/02/github-cherry-picking-commits-from-pull.html. Then commit that branch.
- <a href='https://github.com/Cerfoglg'></a> @VincenzoFerme It won't let me, it still shows all the commits. Creating new branches just bring in all the commits for the properties and stats as well
- <a href='https://github.com/VincenzoFerme'></a> @Cerfoglg are you creating a new branch from your `dev` branch after you synch your `dev` branch with the `dev` branch of the benchflow repository?
- <a href='https://github.com/Cerfoglg'></a> @VincenzoFerme Found a workaround, see #63
- <a href='https://github.com/VincenzoFerme'></a> Closed in favour of https://github.com/benchflow/collectors/pull/63

<a href='https://www.codereviewhub.com/benchflow/collectors/pull/61?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benchflow/collectors/pull/61?approve=1'></a>&nbsp;<a href='https://github.com/benchflow/collectors/pull/61'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by VincenzoFerme** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/benchflow/collectors/pull/61'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by VincenzoFerme** [comment]
@Cerfoglg there is something wrong in this pull request. The changes to the `stats` collectors are committed again. Ping me when solved, please.

**Comment by Cerfoglg** [comment]
@VincenzoFerme It doesn't work, it just keeps all the commits for no reason.

**Comment by VincenzoFerme** [comment]
It seems it is because you actually have those commits in the branch from where you are performing the pull request: https://github.com/Cerfoglg/collectors/commits/faban-collector

It seems that one solution would be to have a new branch and `cherry-pick` only the commits that actually add something new: http://mispdev.blogspot.it/2013/02/github-cherry-picking-commits-from-pull.html. Then commit that branch.

**Comment by Cerfoglg** [comment]
@VincenzoFerme It won't let me, it still shows all the commits. Creating new branches just bring in all the commits for the properties and stats as well

**Comment by VincenzoFerme** [comment]
@Cerfoglg are you creating a new branch from your `dev` branch after you synch your `dev` branch with the `dev` branch of the benchflow repository?

**Comment by Cerfoglg** [comment]
@VincenzoFerme Found a workaround, see #63

**Comment by VincenzoFerme** [comment]
Closed in favour of https://github.com/benchflow/collectors/pull/63

**Comment by VincenzoFerme** [comment]
:+1:

**Pull request closed without merging**
