### PR TITLE
Missing deps for properties

### LINKED ISSUE #56: The Properties Collector Does Not Build
The properties collector was disabled in #54, I enabled it in https://github.com/benchflow/collectors/commit/caffdeafda6dd67ce764b695cda4d4842163546d.

It has an issue with the build: https://travis-ci.org/benchflow/collectors/builds/131199025

Once solved, it should also be enabled on Docker Hub.

### PR DESCRIPTION
**Pull request by Cerfoglg**
Fixes #56
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/benchflow/collectors/pull/57%23issuecomment-220285808%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/57%23issuecomment-220290854%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/57%23issuecomment-220303463%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/57%23issuecomment-220308746%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benchflow/collectors/pull/57%23issuecomment-220285808%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Cerfoglg%20still%20does%20not%20build%22%2C%20%22created_at%22%3A%20%222016-05-19T10%3A24%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40VincenzoFerme%20Not%20sure%20what%20happened.%20This%20should%20fix%20it%22%2C%20%22created_at%22%3A%20%222016-05-19T10%3A50%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40Cerfoglg%20you%20need%20to%20merge%20with%20the%20mainstream%20%60dev%60%20branch%20before%20committing.%20I%20for%20example%20added%20%60https%3A//github.com/benchflow/collectors/blob/dev/.codeclimate.yml%60%20and%20I%20don%27t%20see%20it%20in%20your%20fork.%22%2C%20%22created_at%22%3A%20%222016-05-19T11%3A58%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-19T12%3A24%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/VincenzoFerme%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/VincenzoFerme'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/benchflow/collectors/pull/57#issuecomment-220285808'>General Comment</a></b>
- <a href='https://github.com/VincenzoFerme'></a> @Cerfoglg still does not build
- <a href='https://github.com/Cerfoglg'></a> @VincenzoFerme Not sure what happened. This should fix it
- <a href='https://github.com/VincenzoFerme'></a> @Cerfoglg you need to merge with the mainstream `dev` branch before committing. I for example added `https://github.com/benchflow/collectors/blob/dev/.codeclimate.yml` and I don't see it in your fork.

<a href='https://www.codereviewhub.com/benchflow/collectors/pull/57?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benchflow/collectors/pull/57?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benchflow/collectors/pull/57?approve=0'></a>&nbsp;<a href='https://github.com/benchflow/collectors/pull/57'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by VincenzoFerme** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/benchflow/collectors/pull/57'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by VincenzoFerme** [comment]
@Cerfoglg still does not build

**Comment by Cerfoglg** [comment]
@VincenzoFerme Not sure what happened. This should fix it

**Comment by VincenzoFerme** [comment]
@Cerfoglg you need to merge with the mainstream `dev` branch before committing. I for example added `https://github.com/benchflow/collectors/blob/dev/.codeclimate.yml` and I don't see it in your fork.

**Comment by VincenzoFerme** [comment]
:shipit:

**Pull request merged**
