### PR TITLE
Properties collector

### PR DESCRIPTION
**Pull request by Cerfoglg**
Replaced by #54
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/benchflow/collectors/pull/50%23issuecomment-212881105%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/50%23issuecomment-219878525%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/50%23issuecomment-220088948%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/50%23issuecomment-220089157%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/50%23issuecomment-220089217%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/50%23issuecomment-220089742%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/50%23issuecomment-220089846%22%2C%20%22https%3A//github.com/benchflow/collectors/pull/50%23issuecomment-220089985%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benchflow/collectors/pull/50%23issuecomment-212881105%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22To%20change%3A%5Cr%5Cn-%20Godeps%20dep%20on%20minio-go%20no%20longer%20needed%22%2C%20%22created_at%22%3A%20%222016-04-21T11%3A53%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40Cerfoglg%20we%20need%20to%20restructure%20this%20pull%20request.%20It%27s%20not%20possible%20to%20handle%20it%20like%20this%20because%20I%20cannot%20see%20the%20files%20I%20need%20to%20review.%20So%20please%3A%20make%20a%20copy%20of%20the%20current%20version%20of%20the%20code%2C%20revert%20the%20repository%20to%20https%3A//github.com/benchflow/collectors/pull/50/commits/5ac49624981e1a1de5b03b991cc0a33ff8ff4998%2C%20copy%20back%20all%20the%20files%20from%20the%20copy%20you%20did%2C%20perform%20separated%20commits%20for%20dependencies%20and%20other%20files%20you%20worked%20on.%22%2C%20%22created_at%22%3A%20%222016-05-17T22%3A55%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-05-18T16%3A50%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-18T16%3A51%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%3Agun%3A%22%2C%20%22created_at%22%3A%20%222016-05-18T16%3A51%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-05-18T16%3A53%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22Replaced%20by%20%2354%20%22%2C%20%22created_at%22%3A%20%222016-05-18T16%3A53%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-05-18T16%3A54%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/benchflow/collectors/pull/50#issuecomment-212881105'>General Comment</a></b>
- <a href='https://github.com/Cerfoglg'></a> To change:
- Godeps dep on minio-go no longer needed
- <a href='https://github.com/VincenzoFerme'></a> @Cerfoglg we need to restructure this pull request. It's not possible to handle it like this because I cannot see the files I need to review. So please: make a copy of the current version of the code, revert the repository to https://github.com/benchflow/collectors/pull/50/commits/5ac49624981e1a1de5b03b991cc0a33ff8ff4998, copy back all the files from the copy you did, perform separated commits for dependencies and other files you worked on.
- <a href='https://github.com/VincenzoFerme'></a> :+1:
- <a href='https://github.com/VincenzoFerme'></a> :shipit:
- <a href='https://github.com/VincenzoFerme'></a> :shipit::gun:
- <a href='https://github.com/VincenzoFerme'></a> :+1:
- <a href='https://github.com/VincenzoFerme'></a> Replaced by #54

<a href='https://www.codereviewhub.com/benchflow/collectors/pull/50?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benchflow/collectors/pull/50?approve=1'></a>&nbsp;<a href='https://github.com/benchflow/collectors/pull/50'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Cerfoglg** [comment]
To change:
- Godeps dep on minio-go no longer needed

**Comment by VincenzoFerme** [comment]
@Cerfoglg we need to restructure this pull request. It's not possible to handle it like this because I cannot see the files I need to review. So please: make a copy of the current version of the code, revert the repository to https://github.com/benchflow/collectors/pull/50/commits/5ac49624981e1a1de5b03b991cc0a33ff8ff4998, copy back all the files from the copy you did, perform separated commits for dependencies and other files you worked on.

**Comment by VincenzoFerme** [comment]
:+1:

**Comment by VincenzoFerme** [comment]
:shipit:

**Comment by VincenzoFerme** [comment]
:shipit::gun:

**Comment by VincenzoFerme** [comment]
:+1:

**Comment by VincenzoFerme** [comment]
Replaced by #54

**Comment by VincenzoFerme** [comment]
:+1:

**Pull request closed without merging**
